### ISSUE TITLE
Add loopback-context API docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-context#27]
A [recent PR](https://github.com/strongloop/loopback.io/pull/335) brought to my attention that https://apidocs.strongloop.com/loopback/#loopback-context no longer exists which begs the question: Should we add API docs for this module to https://apidocs.strongloop.com/ ?

**Tasks**
 - [ ] add `docs.json` to this repository
 - [ ] publish a new version
 - [ ] update `apidocs.strongloop.com` configuration to add `loopback-context`

**Comment by bajtos** [comment]
> Should we add API docs for this module to https://apidocs.strongloop.com/ ?

Yes please!

**Comment by bajtos** [comment]
The tasks as I see them

 - [ ] add `docs.json` to this repository
 - [ ] publish a new version
 - [ ] update `apidocs.strongloop.com` configuration to add `loopback-context`

**Comment by crandmck** [comment]
I added `docs.json` to a new branch (28530de25f87cbc9593b04a8b177243647abbb4c) but when I run `sdocs -p` locally I don't see any content.... 

![2017-04-13_1321](https://cloud.githubusercontent.com/assets/2925364/25022847/4b89b610-204c-11e7-9349-f7da2f2d748c.png)

@bajtos Any idea what's going on?

**Comment by crandmck** [comment]
Also added to `repos.json` in apidocs repo - https://github.com/strongloop-internal/apidocs.strongloop.com/pull/72

**Comment by crandmck** [comment]
@hacksparrow @ritch asked if you could please see if you can figure this out.
Checkout my branch `add-api-docs` and see above comment.  

For some reason, strong-docs is not picking up any of the code annotations, though it is seeing the methods.

**Comment by hacksparrow** [comment]
@crandmck @ritch I am familiar with this problem, the current `sdocs` has to be patched to handle this problem; something I can work in the upcoming sprint. However, my recommendation to re-write the bulk of `sdocs`, else we will be building a huge technical debt.

**Comment by crandmck** [comment]
@ritch @hacksparrow 
We should discuss how we want to maintain & improve strong-docs and apidocs. moving forward with loopback-next.  For loopback-next, we'll need the ability to call out to TypeDoc for packages written in TS as well as strong-docs for packages written in JS.

Given Yaapa's comment above
> ... my recommendation to re-write the bulk of sdocs, ...
This might be a good time to think about the best way to consider rewriting it completely.
